# docker-compose.yml

version: '3.7'
services:
  scroogie:
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    ports:
      - '${APP_PORT}:${APP_PORT}'

  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - '35432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/scroogie
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
